#!/bin/bash
#
# Leaves the changes uncommitted in the working tree, so you get to fix any
# unintended changes.
#
# Author: Lasse Karstensen <lkarsten@varnish-software.com>, September 2014.
#
set -o errexit

NAME=$1
if [ -z "$NAME" ]; then
	echo "Usage: $0 <new-vmod-name-without-libvmod-prefix>"
	echo "Rename libvmod-includereq source tree."
	echo
	exit -1
fi

if ! git diff-index --quiet HEAD --; then
	echo "ERROR: Need a clean working tree. Run \"git stash\" first."
	exit -2
fi

git mv src/vmod_includereq.c src/vmod_${NAME}.c
git mv src/vmod_includereq.vcc src/vmod_${NAME}.vcc
git mv vmod-includereq.spec vmod-${NAME}.spec

git grep -z -l includereq | xargs -0 sed -i -s -e "s/includereq/${NAME}/g"

git rm rename-vmod-script

echo "All done."
echo -e "For your cut&paste needs:\n  git commit -a -m \"Automatic rename of libvmod-includereq to libvmod-${NAME}.\""


